version: "3"
services:
    sportsstore:
        build: .
        ports:
            - "5000:5000"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
        depends_on:
            - postgres
    postgres:
        image: "postgres"
        environment:
            SA_PASSWORD: "admin"
            ACCEPT_EULA: "Y"
