version: "3.7"

networks:
  dockerapi-dev:
    driver: bridge #by defult

services:
    shoppingstore:
        container_name: 'shoppingstore'
        image: shoppingstore:latest
        depends_on:
          - "shopdb"
          - "identitydb"
        build:
          context: .
          dockerfile: Dockerfile
        #ports:
          #- "80:80"     
        environment:
          ASPNETCORE_ENVIRONMENT: Production
        networks:
          - dockerapi-dev  
    shopdb:
        container_name: 'shopdb'
        image: postgres:latest
        ports:
            - "5436:5432"
        volumes:
            - shopdb_volume:/var/lib/postgresql/data
            #- ./seed.sql :/docker-entrypoint-initdb.d/seed.sql
        environment:
            POSTGRES_USER: "shop_user"
            POSTGRES_PASSWORD: "password"
        networks:
            - dockerapi-dev

    identitydb:
        container_name: 'identitydb'
        image: postgres:latest
        ports:
            - "5434:5432"
        volumes:
            - identitydb_volume:/var/lib/postgresql/data
        #  - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
        environment:
            POSTGRES_USER: "identity_user"
            POSTGRES_PASSWORD: "password"
        networks:
            - dockerapi-dev
    swag:
        image: ghcr.io/linuxserver/swag
        container_name: swag
        cap_add:
          - NET_ADMIN
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=America/Denver
          - URL=shopping.maksadannamuradov.com
          - SUBDOMAINS=www, admin
          - VALIDATION=http
          - STAGING=true
        volumes:
          - /swag:/config
          - ./default.conf:/config/nginx/site-confs/default
        ports:
          - 443:443
          - 80:80
        depends_on:
          - identitydb
          - shopdb
          - shoppingstore
        networks:
            - dockerapi-dev
        restart: unless-stopped
        extra_hosts:
            - host.docker.internal:host-gateway
volumes:
    shopdb_volume:
    identitydb_volume:
