version: "3.7"

networks:
  dockerapi-dev:
    driver: bridge #by defult

services:
    shoppingstore:
        container_name: 'shoppingstore'
        image: shoppingstore:latest
        depends_on:
          - "shopdb"
          - "identitydb"
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "80:80"     
        environment:
          ASPNETCORE_ENVIRONMENT: Production
        networks:
          - dockerapi-dev  
    shopdb:
        container_name: 'shopdb'
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
            - shopdb_volume:/var/lib/postgresql/data
            #- ./seed.sql :/docker-entrypoint-initdb.d/seed.sql
        environment:
            POSTGRES_USER: "shop_user"
            POSTGRES_PASSWORD: "password"
        networks:
            - dockerapi-dev

    identitydb:
        container_name: 'identitydb'
        image: postgres:latest
        ports:
            - "5434:5432"
        volumes:
            - identitydb_volume:/var/lib/postgresql/data
        #  - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
        environment:
            POSTGRES_USER: "identity_user"
            POSTGRES_PASSWORD: "password"
        networks:
            - dockerapi-dev
    webserver:
        image: nginx:latest
        ports:
          - 80:80
          - 443:443
        restart: always
        volumes:
          - ./nginx/conf/:/etc/nginx/conf.d/:ro
          - ./certbot/www:/var/www/certbot/:ro
volumes:
    shopdb_volume:
    identitydb_volume: