version: "3"

networks:
  dockerapi-dev:
    driver: bridge 

services:
    shoppingstore:
        image: shoppingstore:latest
        depends_on:
          - "shoppingdb"
          - "identitydb"
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "5000:5000"     
        environment:
          ASPNETCORE_ENVIRONMENT: Production
        networks:
          - dockerapi-dev  
    shopdb:
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
          - db_volume:/var/lib/postgresql/data
          - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "admin"
        networks:
            - dockerapi-dev

    identitydb:
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
          - db_volume:/var/lib/postgresql/data
          - ./dbscripts/seed.sql :/docker-entrypoint-initdb.d/seed.sql
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
        networks:
            - dockerapi-dev
volumes:
  db_volume: